spring:
    datasource:
        url: jdbc:mysql://172.20.0.7:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

jpa:
    database: mysql
    show-sql: true
    hibernate:
        ddl-auto: update
        naming:
            strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy

    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            #enable_lazy_load_no_trans: true
       # open-in-view: true